### ISSUE TITLE
Q23734811 - Plantation reported as an object that exists outside physical reality 

### ISSUE THREAD

**Issue by KasperFranz** [osm-quality/wikibrain#10]
A plantation in Denmark is classified as an object that exists outside physical reality when it is just set as a plantation. 

Output
```
== {{Q|Q23734811}} classified as an object that exists outside physical reality ==
{{Q|Q188913}}
:{{Q|Q38112}}
::{{Q|Q11023}}
:::{{Q|Q28797}}
::::{{Q|Q336}}
:::::{{Q|Q105948247}}
::::::{{Q|Q3622126}}
:::::::{{Q|Q7048977}}
```

I am not sure if we should handle this in this package or report it to Wikidata for it to be resolved on their end.

Other examples:
https://openstreetmap.org/relation/10031487
https://openstreetmap.org/relation/11195378
https://openstreetmap.org/relation/1434456
https://openstreetmap.org/relation/3213266

**Comment by matkoniecz** [comment]
Typically I would do both.

Report problem to that page (it is in my userspace but feel free to edit it), and ignore first invalid element of chain on ignored elements.

What we should change is to handle how to handle cases fixed on Wikidata. Previously I was manually clearing it locally on my computer but now that more than one person uses it that becomes less useful (as manually cleared broken item,  is cleared only on one computer).

**Comment by matkoniecz** [comment]
Maybe failing test should clear cache for its items?

So manual cache clearing will not be needed
It will not much cost for running tests as failing tests are fairly rare.

**Comment by matkoniecz** [comment]
Oh  and also new year should be created . I guess this should go somewhere into documentation what should be done

**Comment by matkoniecz** [comment]
https://github.com/osm-quality/wikibrain/blob/master/CONTRIBUTING.md has initial documentation pass, this specific bug should be fixed

please let me know by opening new issue if anything is unclear
