### ISSUE TITLE
not recognigsed operator:wikipedia:en 

### ISSUE THREAD

**Issue by KasperFranz** [osm-quality/wikibrain#3]
While running thos for Denmark I get the following error
> wikipedia tag in outdated form (operator:wikipedia:en), is not using any known language code
[an affected OSM element that may be improved](https://openstreetmap.org/node/2145082434)

For now it might be worth allowing the operator:wikipedia:en until a discussion has happened at community level if such tags are supported

**Comment by matkoniecz** [comment]
`operator:wikipedia` = `en:page name` should be used, right?

That looks like prefixed variant of old-style wikipedia tags

**Comment by KasperFranz** [comment]
It already got operator:wikipedia which is linking to the danish Wikipedia and then it got operator:Wikipedia:en = on top of that

**Comment by matkoniecz** [comment]
In such case validator should recommend to remove `operator:wikipedia:en` as pointless duplicate

Though from looking at https://taginfo.openstreetmap.org/keys/operator%3Awikipedia%3Aen#overview - consulting with local community and mass remove/replace may be a better idea than implementing dedicated support.

This tag family seems rare, see https://taginfo.openstreetmap.org/search?q=%3Awikipedia%3Aen#keys

**Comment by KasperFranz** [comment]
Question raised: https://community.openstreetmap.org/t/mass-edit-suggestion-removing-operatoren/107962
