### ISSUE TITLE
test_that_wikidata_works_with_multiple_brands_one_invalid failing

### ISSUE THREAD

**Issue by matkoniecz** [osm-quality/wikibrain#6]
```
======================================================================
FAIL: test_that_wikidata_works_with_multiple_brands_one_invalid (test_wikimedia_link_issue_reporter.Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mateusz/Documents/install_moje/OSM_software/wikibrain_py_package_published/test_wikimedia_link_issue_reporter.py", line 490, in test_that_wikidata_works_with_multiple_brands_one_invalid
    self.assertIsNone(should_be_fine)
AssertionError: <wikibrain.wikimedia_link_issue_reporter.ErrorReport object at 0x7f24aa898d90> is not None
```

Given that https://www.wikidata.org/wiki/Q7501155 is actually defunct, it should not be None, right? And if one would be invalid then error should be still emitted?

@KasperFranz 

from #5

**Comment by KasperFranz** [comment]
The test case was wrong - I will create a PR to fix it shorly

**Comment by matkoniecz** [comment]
Thanks!

@KasperFranz I invited you with triage rights to this repository, feel free to join if you want (and for some obscure reason I needed to move it to personal organisation from personal account to achieve this, hopefully nothing got mangled by this)

**Comment by KasperFranz** [comment]
> Thanks!
> 
> @KasperFranz I invited you with triage rights to this repository, feel free to join if you want (and for some obscure reason I needed to move it to personal organisation from personal account to achieve this, hopefully nothing got mangled by this)

Interesting, I am not sure what the triage role gives, but thank you :)

**Comment by matkoniecz** [comment]
> I am not sure what the triage role gives

1) you can close/reopen/label all issues

2) you can be assigned to issues (so it was a trap :) )
